# Generated by Django 4.2.4 on 2023-08-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Addition date'),
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=1, verbose_name='Book text'),
            preserve_default=False,
        ),
    ]
